-- To solidify skills on data analysis with SQl, attention will turn on an online sales report for 2 mega brands
-- Focus will be to understand the business models and put some skills to the test.

-- By the end of the project the below should have been touched on exhaustively.
	--Aggregation
	-- Summarizing
	-- Truncating
	-- Cleaning
	-- Labelling
	-- Casting
	-- Common Table expression
	-- Correlation
	-- Working with dates and times
	
-- Also, the below questions should be answered
	-- How do the price points of Nike and Adidas products differ?
	-- Is there a difference in the amount of discount offered between the brands?
	-- Is there any correlation between revenue and reviews? And if so, how strong is it?
	-- Does the length of a product's description influence a product's rating and reviews?
	-- Are there any trends or gaps in the volume of reviews by month?
	-- How much of the company's stock consists of footwear items? What is the median revenue generated by these products?
	-- How does footwear's median revenue differ from clothing products?

-- Creating tabe that will the brand details, Product_id and name of the brand

create table brand(
	product_id text,
	brand_details text
)

copy brand
from 'C:\Users\KEVIN\Desktop\Mongo\Online_Review\brands_v2.csv'
with(format csv, header)

-- Snippet of the data

select * 
from brand 
limit 5

-- Create table for finance

create table finance(
	product_id text,
	listing decimal,
	sale_price decimal,
	discount decimal,
	revenue decimal
)

copy finance
from 'C:\Users\KEVIN\Desktop\Mongo\Online_Review\finance.csv'
with (format csv, header)

-- create table for information

create table information(
	product_name text,
	product_id text,
	description text
)

copy information
from 'C:\Users\KEVIN\Desktop\Mongo\Online_Review\info_v2.csv'
with(format csv, header)

-- Create table for reviews

create table review(
	product_id text,
	rating decimal,
	reviews decimal
)

copy review
from 'C:\Users\KEVIN\Desktop\Mongo\Online_Review\reviews_v2.csv'
with (format csv, header)

select * 
from review
limit 5

-- Create table 
create table traffic(
	product_id text,
	last_visited timestamptz
)

copy traffic
from 'C:\Users\KEVIN\Desktop\Mongo\Online_Review\traffic_v3.csv'
with (format csv, header)


select *
from traffic
limit 5

-- Joining to combine necessary tables together

-- tables to reference and combine
	-- Traffic, review, information, finance, brand
	
	-- Traffic - the table captures website traffic
	-- Review - this how the customers are 
	-- Information - (Product_name, Product, Description)
	-- Finance - captures the sales(revenue, profit and discount)
	-- Brand - basically the product id and brand name


create table sales_report as (
select 
t.product_id,
t.last_visited,
b.brand_details,
i.product_name,
i.description,
r.rating,
r.reviews,
f.listing,
f.sale_price,
f.discount,
f.revenue
from traffic t 
inner join brand b
on b.product_id = t.product_id
inner join information i
on t.product_id = i.product_id
inner join review r
on t.product_id = r.product_id
inner join finance f
on t.product_id = f.product_id
)


select *
from sales_report
limit 5

-- Price comparison between Nike and Adidas
select
round(avg(sale_price),2),
round(avg(listing),2)
from sales_report
where brand_details = 'Adidas'
union
select 
round(avg(sale_price),2),
round(avg(listing),2)
from sales_report 
where brand_details = 'Nike'

-- Pricing based on sales price
-- Average retail price for Adidas is 51.20 
-- Average retail price for Nike is 102.18

-- Pricing based on listing
-- Average retail price for Adidas is 75.73 
-- Average retail price for Nike is 41.34

-- The average retail price for Nike is twice as much as that of Adidas

-- Is there a difference in the amount of discount offered
select 
round(avg(discount),2)
from sales_report
where brand_details = 'Adidas'
union
select 
round(avg(discount),2)
from sales_report
where brand_details = 'Nike'

-- The average discount offered by Nike as brand is negligable as compared to Adidas who offer 0.33 on average

-- Relationship between Revenue and Reviews for either products

select 
corr(revenue, reviews)
from sales_report
where brand_details = 'Adidas'
union
select 
corr(revenue, reviews)
from sales_report
where brand_details = 'Nike'
union
select
corr(revenue, reviews)
from sales_report

-- Correlation between Reviews and Revenue are high, for the overall business, the 2 are highly correlated
-- Suggesting that better reviews leads to better revenue though correlation does not mean causation
-- Correlation for Nike products is almost 1, the same suggests that the 2 influence each other positively,
-- overall correlation -  0.652
-- Addidas correlation - 0.596
-- Nike correlation - 0.946

select 
length(description),
rating,
reviews
from sales_report
where length(description) is not null
group by rating, reviews,length(description)
order by reviews desc, rating desc, length(description) desc

-- 223 is the highest review, it has an average rating of 4.7 and the description is about 133
-- The second rated review is 105, with a rating of 4.3 and the description is 235 words long

select 
length(description),
rating,
reviews
from sales_report
where length(description) is not null
group by rating, reviews,length(description)
order by length(description) desc

--Looking at the description with longest length it has a rating of 3.4 and a review of 18, 
-- same compared to the top reviews, there other things that influence rating and reviews

select 
date_part('month', last_visited),
sum(reviews)
from sales_report
group by date_part('month', last_visited)
order by sum(reviews) desc

-- February, March and January have the highest number of reviews, over 12,000
-- May and November - have less than 8500 cumulative reviews
-- August November and October range between 9000 and 10000

select 
count(brand_details)
from sales_report

-- total count 3120
select
count(brand_details)
from sales_report
where brand_details = 'Nike'
-- Total count Nike - 545

select
count(brand_details)
from sales_report
where brand_details = 'Adidas'
-- addidas - 2575

select
count(brand_details)
from sales_report
where product_name ilike('%Shoes')

-- shoes -- 2259

-- total footwear

select (
(select
count(brand_details)
from sales_report 
where brand_details = 'Nike')+
	(select
count(brand_details)
from sales_report
where product_name ilike('%Shoes')
))::decimal / 
(select count(*)
from sales_report) * 100

-- Footwear is about 88% of the total inventory

-- median revenue generated

select
percentile_cont(.5) 
within group (order by revenue) as median_revenue
from sales_report

-- median revenue generated is 2735.28

-- How does footwear median revenue differ from clothing products

create table adidas as
select
brand_details,
revenue
from sales_report
where product_name ilike('%Shoes%')

create table nike as
select
brand_details,
revenue
from sales_report
where brand_details = 'Nike'

select
percentile_cont(0.5)
within group (order by revenue)
from
(select * from adidas union all select * from nike)

-- Shoe revenue -- 2918.73

-- clothing  median

select
percentile_cont(.5)
within group(order by revenue)
from sales_report
where product_name not ilike('%Shoes%')

-- Median revenue for clothing is 615.26
-- The 2 medians suggest that shoes are expensive as compared to the clothing line. 
































